
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Caine
 */
public class MainScreen extends javax.swing.JFrame {
    private static CheckersController CC = new CheckersController();
    private DefaultListModel tableList = new DefaultListModel();
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        
        openMsgBtn.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e) {
                    CC.AddMessageFrame();
                } });
        createTblBtn.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e) {
                    CC.CreateTable();
                } });
        joinTblBtn.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e) {
                    int i = jList2.getSelectedIndex();
                    CC.JoinTable((int)CheckersController.tableList.get(i));
                } });
    }
    public void Update(){
        tableList.clear();
        
        for (int t=0; t<CheckersController.tableList.size(); t++){
            int n = CheckersController.PlayersOnTbl.get((int)CheckersController.tableList.get(t)).size();
            tableList.addElement(CheckersController.tableList.get(t) + 
                    " ("+n+"/2)");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        playCompBtn = new javax.swing.JButton();
        createTblBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 =  new JList(tableList);
        label4 = new java.awt.Label();
        obsTblBtn = new javax.swing.JButton();
        joinTblBtn = new javax.swing.JButton();
        openMsgBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("CHECKERS GAME!");

        playCompBtn.setText("Play Computer");

        createTblBtn.setText("Create Table");

        jScrollPane4.setViewportView(jList2);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Tables");

        obsTblBtn.setText("Observe Table");

        joinTblBtn.setText("Join Table");

        openMsgBtn.setText("Open Messages");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(obsTblBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(joinTblBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playCompBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createTblBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openMsgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(joinTblBtn)
                        .addGap(15, 15, 15)
                        .addComponent(playCompBtn)
                        .addGap(15, 15, 15)
                        .addComponent(obsTblBtn)
                        .addGap(18, 18, 18)
                        .addComponent(createTblBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openMsgBtn))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
                
            }
        });
    }
    
    
     // Variables declaration - do not modify
    private javax.swing.JButton createTblBtn;
    private static javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton joinTblBtn;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private javax.swing.JButton obsTblBtn;
    private javax.swing.JButton openMsgBtn;
    private javax.swing.JButton playCompBtn;
    // End of variables declaration
/*   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createTblBtn;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton joinTblBtn;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private javax.swing.JButton obsTblBtn;
    private javax.swing.JButton openMsgBtn;
    private javax.swing.JButton playCompBtn;
    // End of variables declaration//GEN-END:variables
*/
 }
